    import { Metadata } from 'next';

    export const metadata: Metadata = {
      title: 'Create Next App',
      description: 'Generated by create next app',
    };

    interface Props {
      children: React.ReactNode
    }

    export default function LayoutServer({ children }: Props) {
      return <>{children}</>
    }